[package]
name = "citation_refiner"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.0"
reqwest = { version = "0.11.16", features = ["blocking"] }
scraper = "0.16.0"
